swaylock \
    --screenshots \
    --clock \
    --indicator \
    --indicator-radius 100 \
    --indicator-thickness 7 \
    --effect-blur 7x5 \
    --effect-vignette 0.5:0.5 \
    --no-unlock-indicator \
    --datestr '' \
    --timestr '%H:%M' \
    --font-size 33 \
    --ignore-empty-password
